### ISSUE TITLE
Generate production calibre assets

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#101]
Looking at my network tab, it looks like `npm start` is creating a 1.01MB bundle.js file, and overall I'm seeing 18 requests, 1,605.07 KB, and 1.79s render time.

**TL;DR:** We should optimize the "Top Activity" thumbnails.

---

The bundle.js isn't surprising since it's unminimized and is filled with about 250 `eval()` statements.

Here's a breakdown of the current assets being thrown into my eyes on the **master** branch:
- **HTML:** 1 request, 1.52KB.
- **CSS:** 2 requests, 34KB (this seems to be a lie, since 27KB of that is fontawesome, which is only about 7KB minimized). -- But clearly we should be minimizing our generated CSS since it contributes 7.21KB.
- **JS:** 1 request, 985KB (AND ONE BUNDLE.JS TO RULE THEM ALL!) -- UglifyJS minification should sort this right out.
- **Fonts:** 1 request, 66KB (fontawesome-webfont.woff2 -- but we've discussed this in previous bugs).
- **Images:** 12 requests, 517KB. This is the red flag. Most images are between 10-20KB (which is still enormous), but the one standout is [desperado-wrap.jpg](https://tctechcrunch2011.files.wordpress.com/2016/02/desperado-wrap.jpg?w=764&h=400&crop=1) which is a 764x400px 356KB image which is being downsized to 40x40px on the client side. We should probably resize and cache these server-side and throw the optimized images on a CDN or something.

![](http://33.media.tumblr.com/f37b00f8f4d1b3de077317302d513eb4/tumblr_inline_o281f8xLFK1r79k32_500.gif)

**Comment by rlr** [comment]
Most or all those images are just placeholder stuff from our fake data. So I don't think there is much to do there. And the rest seems like it will take care of itself like you mentioned.

**Comment by k88hudson** [comment]
Pretty much all the images in the repo are test data and don't need to be optimized, so we should be good for that.

There will need to be some work done here through, primarily around minification; the problem is that no one (that I know of) has yet released a stable minifier that handles es6 features (see https://github.com/mishoo/UglifyJS2/issues/448). So, we have a couple of options:

1. transpile everything down (easier, requires less configuration, but not as efficient/requires unnecessary polyfills)
2. split of dependencies that are already es5 and import them separately (crappy amount of configuration work but ultimately more efficient, not a great option if the es6 code base is rather large)

Minification of css should be (thankfully) easy.

We also need to get the `Define` plugin for Webpack working without minification, if we choose to go route #2

**Comment by k88hudson** [comment]
Also, I am pushing this to milestone 3 (4 might be fine too!)

**Comment by pdehaan** [comment]
Ah yes, i totally get that the current data is placeholders (my browsing history is much less alligator themed), I just wanted to make sure that if I browse a lot of GIFs, that we won't be trying to push down several MB of 800x600 assets and squeezing them into a 40x40px container.

But I'll wait until this is pulling my local browsing history so I can verify.

I tried [unsuccessfully] to run Uglify against the bundle.js (via the webpack flow), but since everything is in a big `eval()` string, it really didn't minify anything and I only saved a few KB.

**Comment by k88hudson** [comment]
Ah yes, we also need to disable source-maps (eval is required for firefox to work)

**Comment by oyiptong** [comment]
Also, please keep in mind that these assets are local.

The addon is distributed zipped up. uglification/minification is not a priority, as the asset package isn't much smaller

**Comment by pdehaan** [comment]
Related #214. Even with real data, we're seeing some pretty big assets being loaded (via embedly results). But not sure if we want to manage our own image proxy where we can host optimized images.
