### ISSUE TITLE
Implement delete history API

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-streams#149]
In #105 we are adding UI for deleting sites. We need a browser api for deleting history items; it should be per URL, and only delete a since instance of it, not all instances of it.

**Comment by oyiptong** [comment]
Let's define that a bit more.

According to the conversation we had yesterday with @nchapman and @bryanbell, we'll make sure that the link displayed on screen gets deleted from history.

However, for Top Sites, the "Site" itself may still exist. Because we group links by hostname then choose the most frecent link to show, the site itself is likely to still show up, albeit with a different link.

From an implementation perspective, this can perhaps be achieved by calling `History.jsm`'s `remove` function. https://dxr.mozilla.org/mozilla-central/rev/d5daf10d3b74b04e8fa63c4e5429de8a0adf79f8/toolkit/components/places/History.jsm#216

We'll have to see if this works for bookmarks as well.

**Comment by oyiptong** [comment]
We need to receive an API message from content with the URL and possibly the type of link, though that might not be necessary.

We won't need a response back, because the PlacesProvider notification will alert all pages of a places removal.

**Comment by oyiptong** [comment]
The philosophy of this is is to make the timeline/newtab page a way to change your history. The previous 'block' functionality was just blocking and only affected the newtab page.

This is about making the 'X' from https://github.com/mozilla/activity-streams/issues/105#issuecomment-186353589 to be a true `Delete` functionality.
