### ISSUE TITLE
Do we want to update immediately if history/bookmarks change?

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-streams#161]
Right now we're not responding to change events in the UI; a refresh (or opening a new tab) is required to reflect changes. We have the history observers hooked up, we just haven't implemented anything in the UI.

What is the best experience here? Do we want to immediately update the UI the user has a tab open and bookmarks something/visits new sites in another tab, then switches back to it? 

Personally I think it makes sense to add or remove new recent sites (for the `Timeline` view) immediately, but I kind of feel like it's ok for `NewTab` not to update, since it's a "selected highlights" kind of thing anyway. That said, maybe we do want to clear stuff if a user deletes their history/a history item or unbookmarks something.

What do you think @nchapman @bryanbell @oyiptong?

Note that the current new tab *does* update immediately.

**Comment by oyiptong** [comment]
I think it's a matter of expectation. The user expects this to work the same way as browser chrome, which should show the most up-to-date view.

If we don't update live, similar to how it works on the web, it means that each instance of the page has potentially a different view, which might be confusing to a user.

**Comment by nchapman** [comment]
To keep things simple, I think we should start with these rules:

1. Never update anything on new tab.
2. Show a notification box at the top of the timeline that lets the user know that there are updates. Clicking it should reveal these updates. @bryanbell will provide a mock.

We can do something more nuanced in the future but this avoids any of the pages changing too much underneath the user.

**Comment by bryanbell** [comment]
![refresh](https://cloud.githubusercontent.com/assets/228979/13412310/37ae8428-def7-11e5-9ef1-f59216421c8c.png)

do this...

**Comment by oyiptong** [comment]
@bryanbell showing that there were X new items is essentially a similar amount of work than actually  showing an updated stream

**Comment by oyiptong** [comment]
What's the rationale behind showing this vs simply showing the new feed items?

It's essentially a browser chrome (instant update) expectation vs a web page expectation (due to high latency/bandwidth, be as lazy as possible).

I think we want the former, not the latter.

**Comment by nchapman** [comment]
@oyiptong sorry for the delay getting back to you. The rationale here is around giving users a stable experience and being careful not to change things out from underneath them (don't gaslight me bro!). Over time I think we'll be able to develop a set of rules which allow us to update parts of the UI without making the user feel disoriented, but for now I would rather us be conservative. I think right now it's riskier for us to automatically update all the UI than it is to update none of the UI. Two examples that come to mind:

1. If the user has scrolled to a specific spot in the timeline and is using it for reference, we'd have to make sure that every history update doesn't change their scroll position (hence the header with update information for now instead of auto updating).

2. Every update to history would potentially cause us to rerun all queries on new tab. This seems like not only a performance problem but also not necessarily what a user would expect. Potentially you would see new tab updating in the background as you browsed or worse it could be changing in front of you during a sync.

I think we should definitely revisit this, but for now I think it's better for us to favor stability.

**Comment by stuartphilp** [comment]
A workflow I might employ is to keep the activity stream open in a pinned tab. As I look at things I would actually like it to auto-update when I come back to the pinned tab rather than refreshing manually. Probably not necessary for V1, but having a toggle/option may be a good idea at some point? Performance-wise a delta/diff or fetch-new-since-timestamp type mechanism might be needed.
