### ISSUE TITLE
Duplicate sites in the same section

### ISSUE THREAD

**Issue by bryanbell** [mozilla/activity-streams#182]
![pasted_image_2_23_16__10_13_am](https://cloud.githubusercontent.com/assets/228979/13261667/16608a5e-da16-11e5-95c8-ec2d3e968a1f.png)

my top sites show twin links to invision.

one for www.invision.com and the other for invision.com.

**Comment by pdehaan** [comment]
I'm also seeing double results in Top Sites for "http://reddit.com" and "https://www.reddit.com".
Similarly, I'm seeing the following dupes in Top Activity for:
- "https://www.reddit.com/", "http://www.reddit.com/", and "http://reddit.com/"
- "https://www.youtube.com/", and "http://www.youtube.com/"

![new_tab](https://cloud.githubusercontent.com/assets/557895/13262471/d281cb46-da19-11e5-9c80-c25d1bed10d7.png)

**Comment by pdehaan** [comment]
So, turns out this is pretty common.
I've visited GitHub.com once in this profile, and it auto-redirects me to the HTTPS version and now I have two Spotlight results and two Top Activity results for github.com.

Same with news.ycombinator.com, one visit, but now duplicate results due to the redirect.
But it is interesting because it could mean potentially I have 4 similar results if I combine HTTP+HTTPS and WWW and no subdomain.

**Comment by oyiptong** [comment]
looks like we need to drop www. and other things when grouping urls
