### ISSUE TITLE
Implement Embedly client in the addon

### ISSUE THREAD

**Issue by oyiptong** [mozilla/activity-streams#258]
This tracks the task to implement an embedly client on the add-on side.

## Embedly client

The embedly client, given a list of urls should:

1. clean up URLs to remove privacy-sensitive information (e.g. HTTP basic auth, many query parameters)
2. check a local disk-based cache for an existing URLs and obtain embedly summary
3. for urls which cause a cache miss, formulate one POST query to send to our embedly client
  * upon receiving a response, store embedly responses in disk-based cache, together with a timestamp
4. return results that have embedly summaries to content

One possible design is to have this embedly cache/request run as a filter that gets called after each DB query results, probably in `lib/ActivityStreams.js`.

For urls it can return immediately, it should send all to content. For urls for which it has no summary, it should send the data without summaries yet.

Content should expect the summaries to be present with a message from chrome and not call out to our proxy directly.

## Asynchronous tasks

We need to run two asynchronous tasks:

1. periodically clean up the disk-based cache. If items are > 24H, the items should be evicted. If we find some data storage that has automatic expiry, this is a moot point. Annotations could be a data store we could use, it's an abstraction on top of sqlite with the notion of expiry
2. on addon boot up, and perhaps every 6 hours, we should trigger all queries that a normal content page load would, and pro-actively prime our caches by running our client

**Comment by oyiptong** [comment]
this will close #5

**Comment by oyiptong** [comment]
Let's ensure that outbound POST requests have a `Content-Type` header of value `application/json`

**Comment by oyiptong** [comment]
@k88hudson has imlemented some URL filtering here that might come in handy for item 1 in the above Embedly Client description: https://github.com/mozilla/activity-streams/blob/master/content-src/lib/filters.js

**Comment by k88hudson** [comment]
I don't know if sending cached items immediately and following up with individual events for enhanced data later is the best experience in this case, since it could result in weird behaviour. For example:

* A partially enhanced array of `History` is sent. While the user is about to click on a `Spotlight` item, content receives an update event for a more recent item, which pushes that `Spotlight` item out of the top 3 and replaces it with the new one

I think we should consider doing this instead:

* if all URLs requested are cached, return the response immediately; if some are missing, only return the response to the client once results from embedly have been received
* reduce the wait time for the above by periodically priming the cache (as you described above)

The downside of this is a slightly longer load time, but I think it's probably better than having weird unexpected behavior from receiving unformatted data and updating it later. Of course, when we collect data in firefox/not embedly, latency won't be an issue.

**Comment by oyiptong** [comment]
Excellent

**Comment by oyiptong** [comment]
I thought content might want to still decide what to do with the data even without previews.

There is a chance no links will be sent to content, and perhaps that's ok too.
The following payload should contain all links and summaries.

**Comment by oyiptong** [comment]
@sarracini also, see https://github.com/mozilla/activity-streams/blob/master/content-src/lib/utils.js#L24

**Comment by k88hudson** [comment]
Note that when this is implemented, we should *not* include the temporary length filter, since this was a temporary stop-gap for using `GET`-style requests (line https://github.com/mozilla/activity-streams/blob/master/content-src/lib/filters.js#L32)
