### ISSUE TITLE
Figure out how we handle errors from embedly

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-streams#439]
If we receive a non-200 response from embedly when fetching links, how should we handle this in the UI? Should we still return the items without enhanced data? Should we re-attempt? Should we notify the user of the error?

**Comment by jaredkerim** [comment]
This is related to https://github.com/mozilla/embedly-proxy/issues/58 as well.

**Comment by oyiptong** [comment]
Currently, if there is an error from the embedly client, the preview just won't get populated.
Should there be no previews obtained, a preview will be requested the next time the url is returned in an API call.

Since we send the link back to content even if we don't have previews, is this still an issue?

**Comment by oyiptong** [comment]
I'm thinking not, so I'm closing the issue. Please feel free to re-open in case we'd want to do something about this.
