### ISSUE TITLE
Persist block list

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-streams#484]
If we have time, we should actually persist the block list or urls (see `BlockUrl` action, `Blocked` reducer) instead of just storing in memory.

At that point, we can remove the alert saying "we're working on this."

**Comment by oyiptong** [comment]
In that case, we should consider using the same mechanism as we do for the newtab page:

Store the data in a pref and send messages between content and the parent.

We'll get the benefit of migrating the existing data. One piece of note, however, is that the block list stores hashes of urls.

It works for links but for "sites" we'll need to define the behavior

**Comment by k88hudson** [comment]
Agreed, that sounds right :+1: 

@oyiptong do we apply the block list to queries in the current newtab page?

**Comment by oyiptong** [comment]
In the current newtab page implementation, this is handled in the parent.

i.e. content will not receive blocked urls. However, the page needs to deal with a page being blocked.

On a tangential topic, here's some food for thought:

The page currently behaves like a web page instead of browser chrome: when the browser state changes, the web page doesn't and requires a refresh for the new state to show.

In the case of a blocked item, the user expects it to behave like browser chrome, i.e. for incremental events to be handled by different instances of the pages.

This is my hypothesis, but I think a blocklist tips the scale towards making the page a "browser-chrome" UI. The potential downsides to seeing a blocked link is high.
