### ISSUE TITLE
Add padding between activity feed and "See all activity" and "Settings" buttons

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#627]
### Steps to reproduce:
1. Browse some stuff.
2. Go to New Tab page.
3. Hover over the last item in the activity feed before the [See all activity] and [Settings] buttons.

### Actual results:
No gap between the hover outline and the buttons.

![new_tab](https://cloud.githubusercontent.com/assets/557895/15000341/0f50fa90-1144-11e6-8d2e-586acfc35551.png)

### Expected results:
"quit touchin' me!"

**Comment by softvision-VladBacia** [comment]
While testing I have encountered the following behavior:

### Steps to reproduce:
1. Browse some stuff.
2. Go to Timeline page.
3. Hover over the item under the last visited item and click on "X" button.
4. Hover over the last visited item.

### Actual results:
The selection overlays are overlapping.
![overlap](https://cloud.githubusercontent.com/assets/9248513/15021389/2a1bc486-122f-11e6-96e1-ff902f6dbc47.jpg)

### Expected results:
The selection overlays and buttons are not overlapping when they are selected.

### Notes:
This issue is reproducible also on New Tab page.
