### ISSUE TITLE
Bookmark urls containing % cause Bookmarks view to not render

### ISSUE THREAD

**Issue by jbuck** [mozilla/activity-streams#646]
I have some bookmarks saved but one of them is causing an error in the add-on code: `URIError: malformed URI sequence PreviewProvider.js:124:79`

I looked through my bookmarks and the problem was my search Bugzilla bookmark: `https://bugzilla.mozilla.org/buglist.cgi?quicksearch=%s`

If I removed the `%` from the bookmark URL then the Bookmarks view in Activity Streams works great.

**Comment by k88hudson** [comment]
@rlr do you want to take a look at this one?

**Comment by rlr** [comment]
:+1:

**Comment by softvision-VladBacia** [comment]
This issue is reproducible also with the following scenario:

[STR]:
1. Visit https://bugzilla.mozilla.org/show_bug.cgi?id=1270762% (do not bookmark it)
2. Click on the "Activity Stream" button from the browser toolbar.
3. Wait for Timeline to display content.

[Actual results]:
- After some seconds only the "Highlights" area is populated with browsed data.
- "Just now" area will not be populated.

[Notes]:
- Bookmarks screen is working as expected.
- After the website with % is deleted from history, "Just now" area will display content.
- This issue is reproducible also on New Tab page.
